### ISSUE TITLE
Error when delete learner's state in staff debug

### ISSUE THREAD

**Issue by xcompass** [ubc/ubcpi#119]
In the LMS environment, under “staff debug” there is an option to erase the problem state for a specific student. This is important, so an author can see how the problem looks like, attempt, erase the attempt, and try again.
This option appears for the PI tool but does not seem to work.

![screenshot](https://cloud.githubusercontent.com/assets/465548/23284831/7da4295e-f9e2-11e6-88ee-0f697fafdfff.png)

**Comment by lenglund** [comment]
This is the only way to enable instructors/instructional teams to see a student preview right now, so resolution would be appreciated.

**Comment by lenglund** [comment]
Likely related to #99.

**Comment by kitsook** [comment]
The issue was that student's submission is not cancelled / marked invalid.  Also, xblock was not notified about the "Delete Learner's State" action.  Similar issue was [discussed at openedx](https://openedx.atlassian.net/browse/ARCH-18).

A new callback `clear_student_state` has been [introduced by edx to fix that](https://github.com/edx/edx-platform/pull/11666/files).  Will implement that for ubcpi.

Also note that if there is no student state to delete (e.g. clicking the "Delete Learner's State" link twice), the error `Failed to delete student state for user. Unknown Error Occurred.` will be displayed, which is normal.
