### ISSUE TITLE
Is django toolbar really a necessary dependency?

### ISSUE THREAD

**Issue by cptvitamin** [ubc/ubcpi#123]
https://github.com/ubc/ubcpi/blob/a132acf0de0ad80fe50c451abac4951d5f6d39a5/requirements/dev.txt

I happened to have django toolbar disabled in my edX devstack and could not import a course that had a ubcpi component in it.  The error message indicated that ucbpi plugin was not installed.  The failed dependency failed silently AFAIK.

**Comment by xcompass** [comment]
The requirement file dev.txt is only needed when doing the development. Did you check if the ubcpi is actually installed? As far as I know, it is not installed by default on devstack since it is in edx-private requirement file: https://github.com/edx/edx-platform/blob/master/requirements/edx/edx-private.txt

**Comment by jleong-openedx** [comment]
Hi @cptvitamin, we are closing this for now; please let us know if you have any further questions/issues.

**Comment by cptvitamin** [comment]
As long as you guys are OK with a silent failure for anyone who imports a course that has a ucbpi component, and who doesn't have django-toolbar enabled, than it's fine by me.
